spring:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  #sql.init.platform: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  h2.console.enabled : true
